### ISSUE TITLE
VCS integration is broken

### ISSUE THREAD

**Issue by uffejakobsen** [MightyCreak/diffuse#120]
VCS integration is broken with the new changes

Place your current dir inside a git repo (the diffuse git repo itself will do)
Try these commands:

    diffuse -c HEAD
    diffuse -c some-sha-from-the-repo

None of the above commands work anymore - 
I wonder if the new release was a bit too quick - unfortunately the release have already been picked up by some distributions (ArchLinux etc)

**Comment by MightyCreak** [comment]
Thanks, I'll watch that!

Are you testing with v0.7.2 or master?

**Comment by MightyCreak** [comment]
Ok well, it seems I have inadvertently fixed the bug by cleaning the code even more :sweat_smile: 

It doesn't work on 0.7.2, but it does work on master.

I'll clean a bit more stuff and push a 0.7.3 later.

**Comment by uffejakobsen** [comment]
Well I was testing both the master and 0.7.2 - and none of them did work at the time...
Will pull master and try again...

**Comment by uffejakobsen** [comment]
I tried master and while `diffuse -c some-git-sha` does seem to work

`diffuse -c HEAD` does still not work

**Comment by MightyCreak** [comment]
When you say it doesn't work, what do you expect it to do?

Because I thought it didn't work until I discovered that HEAD was a merge commit (i.e. no file changed).

If you run `git checkout some-git-sha` and `diffuse -c HEAD`, you should get the same result as `diffuse -c some-git-sha` (that's what I have locally at least)

**Comment by uffejakobsen** [comment]
Ah I did not notice that HEAD was a merge commit either... :-)

**Comment by uffejakobsen** [comment]
I think that this bug can be closed the the changes done for 0.7.3 :-)

**Comment by MightyCreak** [comment]
Cool!

That said, maybe it would be nice to have a dialog window saying that no files were changed in the given commit.. would be a nice enhancement.

**Comment by uffejakobsen** [comment]
Yes, that would be a really nice feature :-)

**Comment by MightyCreak** [comment]
Bug fixed in v0.7.3! :tada:
