### ISSUE TITLE
Can't drag and drop a file in a pane

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/diffuse#14]

**Comment by schinfo** [comment]
This bug has not been fixed until today !!!

**Comment by MightyCreak** [comment]
I know. Drag'n'drop got broken with the migration to GTK3. If you feel like understanding why, that would be wonderful.

**Comment by AJenbo** [comment]
Thanks for fixing this :)

**Comment by Uhter** [comment]
I have the same issue on 0.9.0-1 version!

background:

- Manjaro (Arch Linux based)
- Xfce DE

**Comment by joyously** [comment]
I'm running 0.7.3 on Ubuntu 22.04 LTS with Xfce DE and it works.

**Comment by Uhter** [comment]
Thanks @joyously for your comment :)
But I've decided to use another software.
