### ISSUE TITLE
Button to reload all the files modified externally

### ISSUE THREAD

**Issue by krlmlr** [MightyCreak/diffuse#16]
should show only one dialog, currently shows a message box for each file.

I remember a similar dialog for "Save changed files", perhaps it could be reused?

**Comment by MightyCreak** [comment]
I'm not sure I understand, you'd like to have only one window if you change both files, is that it?

**Comment by krlmlr** [comment]
When `diffuse -m` opens multiple tabs, and I update the working copy (say, `git checkout other-branch`), I'm getting one message box per changed file. I'd prefer a single dialog, or even better, an option to auto-reload (if unchanged).

**Comment by krlmlr** [comment]
This is perhaps the single biggest annoyance in a tool that I'm using with great delight. What's the best way to move forward?

**Comment by MightyCreak** [comment]
Well it's good to know this pet project of mine is still used, thank you ;)

Now that I'm not on Mac anymore, I could take a deeper look into this app again. At least upgrade it with the latest upstream code.

As for your question, I can take a look, but I'm also very open to external PRs if you feel like it: it is basically just one big python file (in src/usr/bin).

**Comment by krlmlr** [comment]
Thanks for the heads up!

I wasn't aware that upstream is still active. If you could merge, I'll try running from source and see if I can contribute. The Ubuntu 18.04 version is from 2014...

**Comment by MightyCreak** [comment]
There isn't much improvements with the latest commits (I merged up to r426): https://sourceforge.net/p/diffuse/code/commit_browser

Why do you mention Ubuntu? I'm not following your train of thought there ;)

**Comment by krlmlr** [comment]
I'm running Ubuntu, which still has diffuse 0.4.8.

**Comment by MightyCreak** [comment]
I understand, so your're actually using the version from the SVN repository (the original author). I made a few tweaks in this Git repo, most notably compatibility with GTK3.
