### ISSUE TITLE
Use GTK3's Gtk.Application/Gtk.ApplicationWindow

### ISSUE THREAD

**Issue by krlmlr** [MightyCreak/diffuse#178]
for native macOS menu.

Follow-up to https://github.com/MightyCreak/diffuse/issues/143#issuecomment-1289928959.

**Comment by MightyCreak** [comment]
For more information: https://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html

**Comment by krlmlr** [comment]
@hugoholgersson: Would you know what needs to be done here?

**Comment by hugoholgersson** [comment]
No, I don't. I only made a similar note in https://github.com/MightyCreak/diffuse/pull/165#issuecomment-1235428388 but I did not dig deeper. 

It would be cool if you'd take a stab. I'd be happy to test and review a PR for this.
