### ISSUE TITLE
Most Toolbar Buttons Do Not Function in Latest Git Builds

### ISSUE THREAD

**Issue by bongochong** [MightyCreak/diffuse#186]
When building from git, since [this commit on Nov 21, 2022](https://github.com/MightyCreak/diffuse/commit/8e32f883ec5987d4a10b8a1186b472fa8457f698), most of the toolbar buttons in the main window do not perform their associated actions ([relevant buttons](https://i.ibb.co/TMVL2SN/Screenshot-from-2022-12-28-17-37-37.png)). Every button except *New 2-Way File Merge* and *New 3-Way File Merge* fails to have an effect when clicked. Menu entries still do work for these actions, so it's a bit puzzling. Tested on Fedora 36 and 37 under the Cinnamon desktop environment. Said toolbar buttons do work in the latest stable release by the way.

**Comment by MightyCreak** [comment]
It comes from one of my refactorings. I'm looking for a proper fix right now. Sorry for the delay.

**Comment by bongochong** [comment]
Awesome! Now I can resume doing git builds for COPR again.

**Comment by MightyCreak** [comment]
There's still #188 which is a bit concerning. Didn't have time today to look at it. Might be very simple to fix... or not 😅

**Comment by bongochong** [comment]
Ah, I'll hang tight then. Thank you for the heads up.
