### ISSUE TITLE
Installation on Debian problems

### ISSUE THREAD

**Issue by GregLawson** [MightyCreak/diffuse#20]
On Debian you need 
> $ sudo apt-get install scrollkeeper

To install run:
> $ sudo python2 ./install.py

as I get the following error with python3:
> File "./install.py", line 90
>     only install/remove files; skip the post install/removal tasks""" % (app_path, options['destdir'], options['prefix'], options['sysconfdir'], options['examplesdir'], options['mandir'], options['pythonbin'])

If I type diffuse, I get: 
> Traceback (most recent call last):
>   File "/usr/local/bin/diffuse", line 120, in <module>
>     import gi
> ModuleNotFoundError: No module named 'gi'

So I tried 
> $ pip `install gi

Got error:
> gtk-update-icon-cache: No theme index file.
> ./install.py: WARNING: Failed to update documentation database with gtk-update-icon-cache.

But the installation seemed to (at least partially) succeed.
I appear to have two versions of diffuse installed now:
> $ whereis diffuse
> diffuse: /usr/bin/diffuse /usr/local/bin/diffuse /usr/share/diffuse /usr/share/man/man1/diffuse.1.gz

> $  python2 /usr/bin/diffuse --version
> Diffuse 0.4.8
> Copyright © 2006-2014 Derrick Moser
> $ python2 /usr/local/bin/diffuse --version
> Diffuse 0.5.0
> Copyright © 2006-2014 Derrick Moser
> Copyright © 2015-2016 Romain Failliot

If I type
> $ python2 /usr/local/bin/diffuse

I get a version 0.50 GUI. But if I type 

> $ python2 /usr/bin/diffuse

I get a version 0.48 GUI.

If I type 
> $ python3 /usr/local/bin/diffuse
> Traceback (most recent call last):
>   File "/usr/local/bin/diffuse", line 120, in <module>
>     import gi
>   File "/home/greg/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
>     print url
>             ^
>  SyntaxError: Missing parentheses in call to 'print'

If I ype
> $ diffuse
> Traceback (most recent call last):
>   File "/usr/local/bin/diffuse", line 120, in <module>
>     import gi
>   File "/home/greg/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
>     print url
>             ^
> SyntaxError: Missing parentheses in call to 'print'

At this point I'm confused as print without parenthesis is a python2 problem and I think I using python3. 

Many of these installation problems could be solved by a debian package, which presumable worked for the previous version. I guess I'll take a look at it, though I've been dreading having to learn that level of detail.

I have a work-around to run either version of diffuse, so I guess I'll try the new version and see if anything has changed.

**Comment by MightyCreak** [comment]
Hello!

This is weird indeed.. I thought I would have found a `print` that I missed in the conversion pass to Python 3 on line 120, but there is just the `import gi` there.

That being said, it seems that you are missing the GObject introspection package which should be under the `pygobject` pip package and not `gi` as you mentioned.

On my Fedora 26:

```
~ pip3 show pygobject
Name: pygobject
Version: 3.24.1
Summary: Python bindings for GObject
Home-page: http://www.pygtk.org/
Author: James Henstridge
Author-email: james@daa.com.au
License: GNU LGPL
Location: /usr/lib64/python3.6/site-packages
Requires:
```

Try to install this package and see how it goes.

Thanks!

**Comment by GregLawson** [comment]
I get:
> $ pip3 show pygobject
> bash: pip3: command not found
> $ pip show pygobject
> $ pip install pygobject
> Collecting pygobject
>   Could not find a version that satisfies the requirement pygobject (from versions: )
> No matching distribution found for pygobject

Perhaps I've got a conflict between Debian, Anaconda, and pip world views. I will see if I can install python3 via the Debian package system.
Oops, I got:
> sudo dpkg --configure -a
> dpkg: error: unable to access dpkg status area: Read-only file system

The only good cure for a Read-only file system, I know is a system reboot.
Back later.
Thanks.

**Comment by MightyCreak** [comment]
With all the fixes that's been merged recently, do you still have your issue?

**Comment by MightyCreak** [comment]
Ping @GregLawson ?

**Comment by MightyCreak** [comment]
No worries, but I'll close this issue as I haven't received an answer in 15 days.
