### ISSUE TITLE
ImportError: cannot import name 'util' from 'distutils'

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/diffuse#215]
This one might be for you @debalance ?

There is a missing dependency in the Debian package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034904

It seems that simply adding the package python3-distutils is enough to fix the issue.

**Comment by MightyCreak** [comment]
They're using the old v0.7.7, so maybe you fixed it since then?

**Comment by debalance** [comment]
Indeed: https://salsa.debian.org/debian/diffuse/-/commit/73c4b65f711994e6cda45eae318a55d51c3d2771
I have not made a new upload yet though.

**Comment by debalance** [comment]
This is fixed in Debian testing + unstable, so IMO this issue can be set to done.

**Comment by MightyCreak** [comment]
Ok so apparently the `distutils` package has been removed from [Python 3.12](https://docs.python.org/3/whatsnew/3.12.html):
> the distutils package has been removed from the standard library.

And after looking a better look at it, it's weird that diffuse uses `distutils` in the main source code (as it seems to be intended for setup scripts apparently).

I'll take a look at that.
