### ISSUE TITLE
VCS repo diff operations does not work in this fork of diffuse

### ISSUE THREAD

**Issue by uffejakobsen** [MightyCreak/diffuse#26]
VCS repo diff operations does not work in this fork of diffuse

This fork of diffuse seems quite broken in its current state

The only thing that seems to work is plain traditional file-to-file diffs.

All the advanced VCS repo diff stuff that made diffuse amazing compared to the other "plain file-to-file differs" seems to be broken in this fork.

So far I've encountered that "diffuse -m" and "diffuse -c <git-sha>" within a git repo does not at all

Steps to reproduce:

- change dir into a git repo that has uncommitted changes to files (that are added to the git repo)
  - verify that there are uncommitted changes with git commands such as "git status" and "git diff"
- now run "diffuse -m" to see the same (uncommitted) modifications in diffuse.

result is:
```
Traceback (most recent call last):
  File "src/usr/bin/diffuse", line 8507, in <module>
    funcs[mode](specs, labels, options)
  File "src/usr/bin/diffuse", line 8020, in createModifiedFileTabs
    for specs in vcs.getFolderTemplate(self.prefs, names):
  File "src/usr/bin/diffuse", line 1882, in getFolderTemplate
    for s in popenReadLines(self.root, args, prefs, 'git_bash', [0, 1]):
  File "src/usr/bin/diffuse", line 1373, in popenReadLines
    return strip_eols(splitlines(popenRead(dn, cmd, prefs, bash_pref, success_results)))
  File "src/usr/bin/diffuse", line 262, in splitlines
    j = s.find('\n', i)
TypeError: argument should be integer or bytes-like object, not 'str'
zsh: exit 1     src/usr/bin/diffuse -m
```

**Comment by MightyCreak** [comment]
Merged! Thank you!

**Comment by uffejakobsen** [comment]
Thx :-)

**Comment by uffejakobsen** [comment]
FYI: The ArchLinux has also integrated the pending pull request/patch #24 into their package
It drastically reduces the warnings reported in issue #25 - so it would be nice to have.
FYI: The patches in combination works fine on Arch Linux :-)

**Comment by MightyCreak** [comment]
Good to know, thank you!
Don't hesitate to let me know if something fails on Arch ;)
