### ISSUE TITLE
Release request (like 0.5.0-alpha.8)

### ISSUE THREAD

**Issue by dimaburmistrov** [MightyCreak/diffuse#42]
Hi there!

I'd like to package your project for Void Linux, but this project guides to use releases (and not branches) for referencing code.

And `0.5.0-alpha.7` release had a bug in ruby syntax file (but is already fixed in active branch).

So can I ask you to spawn a new version (with new code & bug fixes)?

**Comment by MightyCreak** [comment]
Hello!

I'll see what I can do, my issue was with Windows, but since I don't have a Windows at hand nowadays, I think I'll make a new release only for Linux (knowing anyone can simply fire up the python script on any other OS).

**Comment by dimaburmistrov** [comment]
That would be great. Thanks!

**Comment by MightyCreak** [comment]
So I tagged the first beta: [v0.5.0-beta.1](https://github.com/MightyCreak/diffuse/releases/tag/v0.5.0-beta.1)

As said previously, there is no Windows release with this one. Is it OK with you?

**Comment by dimaburmistrov** [comment]
Yes, thank you very much!
