### ISSUE TITLE
installing beta with existing previous version

### ISSUE THREAD

**Issue by joyously** [MightyCreak/diffuse#45]
I'm on  Ubuntu Studio 20.04 and I had installed Diffuse from the master branch 25 days ago.
I downloaded the zip file for the [beta](https://github.com/MightyCreak/diffuse/archive/v0.5.0-beta.1.zip) and tried to install it like I did before.
```
Performing install with:
    destdir=/
    prefix=/usr/local/
    sysconfdir=/etc/
    examplesdir=/etc/
    mandir=/usr/local/share/man/
    pythonbin=/usr/bin/env python
Installing /usr/local/bin/diffuse
Traceback (most recent call last):
  File "./install.py", line 230, in <module>
    processFiles(install, os.path.join(destdir, prefix[1:]), 'src/usr/', {
  File "./install.py", line 146, in processFiles
    f = open(d, 'wb')
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/diffuse'
```

Is it expected that the existing installation causes a problem for the new one? Do I have to remove it first?
Of course, I hit Enter too soon... I used `sudo` and it worked (Duh).
But it does say
```
gtk-update-icon-cache /usr/local/icons/hicolor
gtk-update-icon-cache: No theme index file.
./install.py: WARNING: Failed to update documentation database with gtk-update-icon-cache.
WARNING: scrollkeeper-update is not installed
```
I don't know if those are related to Diffuse since there is another message that is _not_ related, when doing the update-desktop-database part.

**Comment by MightyCreak** [comment]
Thanks for the report, I'll investigate that!

**Comment by MightyCreak** [comment]
Ok, so I've looked into it and detected a few issues in the install/uninstall script, nothing important though (see #46).

The few messages that you have at the end are merely warnings. Nothing to worry about actually. From my understanding, and don't forget that I am not the original author of this app :wink:, the call to `gtk-update-icon-cache` doesn't seem to be needed (I would need the explanation of a GNOME expert on this one). As for `scrollkeeper-update`, this seems to be a very old tool to create "documentation metadata".. whatever that means. Here's the website: http://www.ibiblio.org/osrt/omf/

Anyway, I think I'll end up pushing diffuse on PyPi, which will probably remove all this non sense.

**Comment by MightyCreak** [comment]
I'll consider this issue closed since I don't think I can do more for now.

Cheers! ;)
