### ISSUE TITLE
Version Control compares

### ISSUE THREAD

**Issue by joyously** [MightyCreak/diffuse#60]
I have a question and an enhancement to propose.
First, the question is about Bazaar. Since it is now Breezy, I can go in the Preferences and change the command from bzr to brz and it seems to work. But that is probably because it is a pre-existing repo with a .bzr folder. I haven't tried Diffuse on a new repo, but I would think it's looking for .bzr and not .brz. If I change the preference for the order of version control systems to check, to use brz where it had bzr, it does not recognize that there is a version control at all.

Second, the enhancement is about once you are in a compare of a file with a revision, it would be so nice to be able to switch to a different revision, just like you can load a different file. I am envisioning arrow buttons to go between revisions.

**Comment by MightyCreak** [comment]
Hi @joyously !

For better tracking, I've split the second proposition into its own issue: #63 

You're first point is still very relevant and it would be nice of you to reformulate the title and the description to focus on that, or, if you prefer, I can do that.

**Comment by joyously** [comment]
I have tried creating a new repo with Breezy, and it creates a .bzr folder, so apparently they kept that the same. So my original question is moot I think.

**Comment by MightyCreak** [comment]
Perfect, I'll close this issue then. Feel free to reopen it if the issue happens.
