### ISSUE TITLE
Distribute Diffuse on Flathub

### ISSUE THREAD

**Issue by MightyCreak** [MightyCreak/diffuse#65]
Flatpak is becoming a common packaging system across most of the main Linux distributions (Fedora, Ubuntu, Arch, ...). Having Diffuse packaged with Flatpak and distributed on Flathub would help a lot the users wanting to use or even just test Diffuse on their system.

**Comment by MightyCreak** [comment]
The Flathub submission is on the way: https://github.com/flathub/flathub/pull/1961

**Comment by freddii** [comment]
Issue can be closed :)
