### ISSUE TITLE
Pyton 3.8 and above - No module named 'gi'

### ISSUE THREAD

**Issue by pornmailbox** [MightyCreak/diffuse#69]
Hi. I use gentoo. all dependencies installed correctly.
Switching to python version 3.8 and above results in the following error:
 
Traceback (most recent call last):
  File "/usr/local/bin/diffuse", line 120, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

Like [https://github.com/MightyCreak/diffuse/issues/62](url), but PyGObject installed.

Only downgrade of python to 3.7 solves issue.

**Comment by MightyCreak** [comment]
Have you reinstalled PyGObject with `pip` using python 3.8?

**Comment by pornmailbox** [comment]
Hi.
Installation of dev-python/pip solved the issue.
I added this dependency to my ebuild.
thank you.
