### ISSUE TITLE
New Icon suggestion for Diffuse

### ISSUE THREAD

**Issue by creepertron95** [MightyCreak/diffuse#73]
Currently the icon is a [photograph of a giraffe.](https://github.com/MightyCreak/diffuse/blob/master/src/usr/share/icons/hicolor/256x256/apps/diffuse.png) and I wanted to suggest a new icon created in the [GNOME icon style.](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en) I attached an svg for the icon below.

![com github mightycreak Diffuse](https://user-images.githubusercontent.com/53346722/100816604-174b6100-340c-11eb-8541-fc280e6aa491.png)

[com.github.mightycreak.Diffuse.zip](https://github.com/MightyCreak/diffuse/files/5626427/com.github.mightycreak.Diffuse.zip)

**Comment by MightyCreak** [comment]
Oh wow! This is awesome!

It still has the giraffe shape and color, while clearly easier to understand it's a diff tool, and the shape of the icon looks like a construction sign (which is pretty much the state of your project when you're using a diff tool :wink: )!

Thank you very much! I'd be glad to add this icon in the next release.

**Comment by freddii** [comment]
papirus-icon-theme is using this image for diffuse:

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/32x32/apps/diffuse.svg

**Comment by MightyCreak** [comment]
@freddii it is nice too, though I prefer @creepertron95's as it is more in line with GNOME icons guidelines. Papirus is a bit more stylized, which surely fits perfectly within the other Papirus icons, but wouldn't fit as well within the GNOME default theme.

That said, both are better than the actual icon :wink:

**Comment by freddii** [comment]
🙂

**Comment by jimmac** [comment]
The fork metaphor seems quite applicable for a version control app, but a merge tool might need to better communicate the opposite direction. Before trying that, I've explored another metaphor myself, being closer to the literal UI of the app:

**Comment by jimmac** [comment]
This is how it would look like in fullcolor and symbolic

![image](https://user-images.githubusercontent.com/14821/101824020-ef56ae80-3b2b-11eb-89ec-d5f6dbd16740.png)

**Comment by joyously** [comment]
All three look meaningless to me, but then so is a giraffe.
The tool is diff and merge, not one or the other, and definitely not version control.

**Comment by creepertron95** [comment]
We should vote on the icon proposals presented here by me and @jimmac.

**Comment by freddii** [comment]
> This is how it would look like in fullcolor and symbolic
> 
> ![image](https://user-images.githubusercontent.com/14821/101824020-ef56ae80-3b2b-11eb-89ec-d5f6dbd16740.png)
Maybe arrows  ( -> and <- ) bigger, like the + and - from calculator on the same image.

**Comment by jimmac** [comment]
>Maybe arrows ( -> and <- ) bigger, like the + and - from calculator on the same image.

![image](https://user-images.githubusercontent.com/14821/101884265-b274d100-3b98-11eb-8e6b-7113216271b8.png)

**Comment by MightyCreak** [comment]
Indeed there are some very good points here. I agree that, although I like @creepertron95's icon for its similarities with the original giraffe icon, the branching analogy does not really reflect the purpose of the tool. That said, we could argue that without branching there would not be diffs or merges to do.

I liked the colorfulness of @creepertron95's icon. With @jimmac's icon I feel like it reflects exactly what the tool does, but to be fair the same icon could be applied to any diff tool. If you look at http://meldmerge.org/ the icon reflect the "meld" symbolism.

I like @jimmac's icon for its usefulness, in a glimpse of the eye you understand what you'll have.

So, in the end, I wonder if there could be a way to give that little twist to our icon that would make the user thinks "ah, this is Diffuse".

To be clear, I'm not asking anyone to do anything, I appreciate the work already done to produce these icons. I'm merely laying down my thought process. If by any chance this gives you ideas, that's but a nice side-effect :wink:

**Comment by creepertron95** [comment]
I like @jimmac's icon as well. He is after all, one of the main contributors to Adwaita icon theme(and I think Tango as well, ancient but, one of my favorites). Though I wanted to ask, is there a way to somehow incorporate "giraffe" colors into your icon?

**Comment by freddii** [comment]
Yes maybe something like this.
![com github mightycreak Diffusev2](https://user-images.githubusercontent.com/7213207/101935558-95172580-3bdf-11eb-8e65-f7e1857632e2.png)
[com.github.mightycreak.Diffusev2.svg.zip](https://github.com/MightyCreak/diffuse/files/5680679/com.github.mightycreak.Diffusev2.svg.zip)

**Comment by MightyCreak** [comment]
I quite like these colors!

For the reference, here's the original  icon:
![diffuse icon](https://raw.githubusercontent.com/MightyCreak/diffuse/master/src/usr/share/icons/hicolor/256x256/apps/diffuse.png)

What do you think @jimmac ?

**Comment by MightyCreak** [comment]
There is also one thing that I particularly like on Diffuse that most of the other diff tools don't do: the diff blocks have the same heights between the left and right documents, so you don't have this funnel shape that most other diff tools have. Maybe it would be nice to have that represented as well in the icon.

Here's an example of the "same heights" I'm talking about:

On Diffuse:
![image](https://user-images.githubusercontent.com/6382548/101994260-111c7680-3c8f-11eb-8a59-c94be25b6338.png)

On Meld:
![image](https://user-images.githubusercontent.com/6382548/101994309-7f613900-3c8f-11eb-84a3-9c28a552908a.png)

**Comment by MightyCreak** [comment]
I modified a bit the SVG using @jimmac's design with @freddii's colors and I redesigned a bit the "diffs" so that the left and right side have the same height. I also added @jimmac's symbolic icon.

It would be awesome if you could review the PR #87. 

Thank you!!
