### ISSUE TITLE
A request cum suggestion

### ISSUE THREAD

**Issue by hakerdefo** [MightyCreak/diffuse#74]
Since the original version of diffuse has been removed from both Debian testing and Debian unstable because of,
`ROM; release critical bugs, upstream unresponsive`
https://tracker.debian.org/news/1078192/removed-048-4-from-unstable/
https://tracker.debian.org/news/1073789/diffuse-removed-from-testing/

Don't you think your fork of diffuse should be part of Debian repos? It'll be great.
Cheers!!!

**Comment by MightyCreak** [comment]
Hello!
Yes, I'm slowly working towards that, but I don't have a lot of time. Thankfully people are helping me out as you can see here: #68 

Closing this issue as it's a duplicate. Feel free to follow the other issue.

Cheers!

**Comment by hakerdefo** [comment]
@MightyCreak 
It'll be great as Ubuntu itself is based upon Debian so a vast majority of GNU/Linux users will benefit from it.
Cheers!!!
