### ISSUE TITLE
Add install prebuild flatpak to readme

### ISSUE THREAD

**Issue by freddii** [MightyCreak/diffuse#83]
sudo apt-get install flatpak -y
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install --user io.github.mightycreak.Diffuse -y

**Comment by MightyCreak** [comment]
It's actually even easier now that the app has been approved, just this will work (if you already have [flathub installed](https://flatpak.org/setup/)):

    flatpak install io.github.mightycreak.Diffuse

Or you can use GNOME Software:

![Capture d’écran de 2020-12-11 08-12-35](https://user-images.githubusercontent.com/6382548/101907511-aaad3080-3b88-11eb-80e7-fddacdfa618d.png)

**Comment by MightyCreak** [comment]
But I agree with you, I should add more instructions in the readme!
